package ltd.newbee.mall.entity;

import java.io.Serializable;
import java.util.Date;

public class Review implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_new_mall_review.id
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_new_mall_review.content
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_new_mall_review.goods_id
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_new_mall_review.user_id
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_new_mall_review.create_time
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_new_mall_review
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_new_mall_review.id
     *
     * @return the value of tb_new_mall_review.id
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_new_mall_review.id
     *
     * @param id the value for tb_new_mall_review.id
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_new_mall_review.content
     *
     * @return the value of tb_new_mall_review.content
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_new_mall_review.content
     *
     * @param content the value for tb_new_mall_review.content
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_new_mall_review.goods_id
     *
     * @return the value of tb_new_mall_review.goods_id
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_new_mall_review.goods_id
     *
     * @param goodsId the value for tb_new_mall_review.goods_id
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_new_mall_review.user_id
     *
     * @return the value of tb_new_mall_review.user_id
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_new_mall_review.user_id
     *
     * @param userId the value for tb_new_mall_review.user_id
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_new_mall_review.create_time
     *
     * @return the value of tb_new_mall_review.create_time
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_new_mall_review.create_time
     *
     * @param createTime the value for tb_new_mall_review.create_time
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}