package ltd.newbee.mall.dao;


import ltd.newbee.mall.entity.Review;
import ltd.newbee.mall.entity.ReviewExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_new_mall_review
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    long countByExample(ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_new_mall_review
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    int deleteByExample(ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_new_mall_review
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_new_mall_review
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    int insert(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_new_mall_review
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    int insertSelective(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_new_mall_review
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    List<Review> selectByExample(ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_new_mall_review
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    Review selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_new_mall_review
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    int updateByExampleSelective(@Param("record") Review record, @Param("example") ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_new_mall_review
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    int updateByExample(@Param("record") Review record, @Param("example") ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_new_mall_review
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    int updateByPrimaryKeySelective(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_new_mall_review
     *
     * @mbg.generated Sat Sep 25 21:33:09 CST 2021
     */
    int updateByPrimaryKey(Review record);

}